server:
  port: 8888

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
      minimum-idle: 3

